import React, { useMemo, useRef, useState } from 'react';
import { SiteHeroSlide, HeroTextBox, HeroButton } from '../types';
import { uploadHeroArtwork } from '../firebase';
import { Eye, EyeOff, ImagePlus, Monitor, Plus, Smartphone, Trash2, GripVertical } from 'lucide-react';

interface Props { slides: SiteHeroSlide[]; onChangeSlides: (slides: SiteHeroSlide[]) => void; brandName?: string; initialDevice?: 'desktop' | 'mobile'; categories?: unknown[]; collections?: unknown[]; }
type Device = 'desktop' | 'mobile';
const makeBoxes = (s: SiteHeroSlide): HeroTextBox[] => s.textBoxes || [
  { id: `${s.id}-title`, text: [s.title, s.highlight].filter(Boolean).join(' '), x: 8, y: 32, width: 70, fontFamily: 'sans', fontSize: 48, fontWeight: 800, color: s.titleColor || '#fff', align: 'left', visible: s.showText !== false },
  { id: `${s.id}-subtitle`, text: s.subtitle || '', x: 8, y: 55, width: 55, fontFamily: 'sans', fontSize: 18, fontWeight: 400, color: s.subtitleColor || '#fff', align: 'left', visible: Boolean(s.subtitle) && s.showText !== false },
];
const makeButton = (s: SiteHeroSlide): HeroButton => s.button || { id: `${s.id}-button`, label: s.buttonText || 'Khám phá ngay', x: 8, y: 76, width: 24, visible: s.showButton !== false, destinationType: s.categoryLink === 'event_0209' ? 'event' : 'category', destination: s.categoryLink || 'all', backgroundColor: s.buttonBgColor || '#fff', textColor: s.buttonTextColor || '#0f172a', style: s.buttonStyle || 'pill' };
const normalize = (list: SiteHeroSlide[]) => list.map((s, i) => ({ ...s, order: i + 1, isActive: s.isActive !== false, textBoxes: makeBoxes(s), button: makeButton(s) }));
const clamp = (n: number, max = 94) => Math.max(0, Math.min(max, n));

export function CanvaSlideStudio({ slides, onChangeSlides, initialDevice = 'desktop' }: Props) {
  const [selectedId, setSelectedId] = useState(slides[0]?.id || '');
  const [device, setDevice] = useState<Device>(initialDevice);
  const [selectedLayer, setSelectedLayer] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const drag = useRef<{ id: string; x: number; y: number } | null>(null);
  const items = useMemo(() => normalize(slides), [slides]);
  const active = items.find(s => s.id === selectedId) || items[0];
  if (!active) return <button className="rounded-2xl border border-dashed p-10 font-bold" onClick={() => onChangeSlides(normalize([{ id: `slide-${Date.now()}`, tag: '', title: 'New billboard', highlight: '', subtitle: '', bgImage: '', buttonText: 'Explore', categoryLink: 'all', order: 1, isActive: true }]))}>Create first billboard</button>;
  const boxes = makeBoxes(active); const button = makeButton(active); const image = device === 'mobile' ? active.bgImageMobile || active.bgImage : active.bgImage;
  const patch = (change: Partial<SiteHeroSlide>) => onChangeSlides(normalize(items.map(s => s.id === active.id ? { ...s, ...change } : s)));
  const patchLayer = (id: string, change: Partial<HeroTextBox>) => patch({ textBoxes: boxes.map(b => b.id === id ? { ...b, ...change } : b) });
  const patchButton = (change: Partial<HeroButton>) => patch({ button: { ...button, ...change } });
  const addBox = () => { const b: HeroTextBox = { id: `${active.id}-text-${Date.now()}`, text: 'New text', x: 12, y: 68, width: 50, fontFamily: 'sans', fontSize: 24, fontWeight: 600, color: '#fff', align: 'left', visible: true }; patch({ textBoxes: [...boxes, b] }); setSelectedLayer(b.id); };
  const onPointerDown = (e: React.PointerEvent, id: string) => { e.stopPropagation(); const rect = (e.currentTarget.parentElement as HTMLElement).getBoundingClientRect(); drag.current = { id, x: e.clientX - rect.left, y: e.clientY - rect.top }; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId); setSelectedLayer(id); };
  const onPointerMove = (e: React.PointerEvent) => { if (!drag.current) return; const rect = (e.currentTarget as HTMLElement).getBoundingClientRect(); const x = clamp(((e.clientX - rect.left) / rect.width) * 100); const y = clamp(((e.clientY - rect.top) / rect.height) * 100, 92); if (drag.current.id === button.id) patchButton({ x, y }); else patchLayer(drag.current.id, { x, y }); };
  const onPointerUp = () => { drag.current = null; };
  const upload = async (file?: File) => { if (!file || !file.type.startsWith('image/')) return; setUploading(true); try { const url = await uploadHeroArtwork(file, active.id, device); patch(device === 'mobile' ? { bgImageMobile: url, originalBgImageMobile: url } : { bgImage: url, originalBgImage: url }); } finally { setUploading(false); } };
  const addSlide = () => { const id = `slide-${Date.now()}`; onChangeSlides(normalize([...items, { id, tag: '', title: 'New billboard', highlight: '', subtitle: 'Add a description', bgImage: '', buttonText: 'Explore', categoryLink: 'all', order: items.length + 1, isActive: true }])); setSelectedId(id); };
  const removeLayer = (id: string) => patch({ textBoxes: boxes.filter(b => b.id !== id) });
  const destinationOptions = ['all', 'event_0209', 'path:/shop', 'path:/collections', 'external:https://example.com'];
  return <div className="overflow-hidden rounded-[28px] border border-slate-200 bg-[#f6f3ee] text-slate-950 shadow-xl">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b bg-white px-6 py-5"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-amber-700">Billboard studio</p><h2 className="text-2xl font-black">Design your homepage</h2></div><div className="flex gap-2"><button className={`rounded-full px-4 py-2 text-xs font-bold ${device === 'desktop' ? 'bg-slate-950 text-white' : 'bg-slate-100'}`} onClick={() => setDevice('desktop')}><Monitor className="mr-1 inline size-4" />Desktop</button><button className={`rounded-full px-4 py-2 text-xs font-bold ${device === 'mobile' ? 'bg-slate-950 text-white' : 'bg-slate-100'}`} onClick={() => setDevice('mobile')}><Smartphone className="mr-1 inline size-4" />Mobile</button><button className="rounded-full bg-amber-400 px-4 py-2 text-xs font-black" onClick={addSlide}><Plus className="mr-1 inline size-4" />Add slide</button></div></header>
    <div className="grid lg:grid-cols-[210px_minmax(0,1fr)_300px]">
      <aside className="border-b bg-white p-4 lg:border-b-0 lg:border-r"><div className="mb-3 flex justify-between text-xs font-black uppercase tracking-widest"><span>Slides</span><span>{items.length}</span></div><div className="flex gap-2 overflow-auto lg:flex-col">{items.map((s, i) => <button key={s.id} onClick={() => { setSelectedId(s.id); setSelectedLayer(null); }} className={`flex min-w-44 items-center gap-2 rounded-xl border p-2 text-left ${s.id === active.id ? 'border-amber-400 bg-amber-50' : 'border-slate-200'}`}><div className="size-12 shrink-0 overflow-hidden rounded-lg bg-slate-200">{s.bgImage && <img src={s.bgImage} alt="" className="size-full object-cover" />}</div><span className="truncate text-xs font-bold">{i + 1}. {s.title || 'Untitled'}</span>{s.isActive ? <Eye className="size-4 text-emerald-600" /> : <EyeOff className="size-4 text-slate-400" />}</button>)}</div></aside>
      <main className="bg-[#20252b] p-5 text-white"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-white/50">{device === 'desktop' ? 'Desktop artboard · 16:9' : 'Mobile artboard · 9:16'}</p><p className="font-bold">Drag any layer directly on the canvas</p></div><button className="rounded-full border border-white/20 px-3 py-2 text-xs" onClick={() => patch({ isActive: !active.isActive })}>{active.isActive ? 'Visible' : 'Hidden'}</button></div><div className={`relative mx-auto w-full overflow-hidden rounded-2xl bg-slate-700 shadow-2xl ${device === 'mobile' ? 'aspect-[9/16] max-w-[330px]' : 'aspect-[16/9]'}`} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerLeave={onPointerUp} onClick={() => setSelectedLayer(null)}>{image ? <img src={image} alt="Billboard preview" className="absolute inset-0 size-full object-cover" style={{ objectPosition: `${device === 'mobile' ? active.bgPositionXMobile ?? 50 : active.bgPositionX ?? 50}% ${device === 'mobile' ? active.bgPositionYMobile ?? 50 : active.bgPositionY ?? 50}%` }} /> : <div className="absolute inset-0 grid place-items-center text-sm text-white/60">Upload an image from the inspector</div>}<div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/10" />{boxes.map(b => b.visible && <button key={b.id} onPointerDown={e => onPointerDown(e, b.id)} onClick={e => e.stopPropagation()} className={`absolute cursor-move rounded-lg border border-dashed px-2 py-1 text-left ${selectedLayer === b.id ? 'border-amber-300 bg-black/25' : 'border-transparent hover:border-white/70'}`} style={{ left: `${b.x}%`, top: `${b.y}%`, width: `${b.width}%`, color: b.color, fontFamily: b.fontFamily === 'serif' ? 'Georgia,serif' : b.fontFamily === 'mono' ? 'monospace' : 'system-ui', fontSize: `clamp(12px, ${b.fontSize / 14}vw, ${b.fontSize}px)`, fontWeight: b.fontWeight, textAlign: b.align }}>{b.text || 'Empty text'}</button>)}{button.visible && <button onPointerDown={e => onPointerDown(e, button.id)} onClick={e => e.stopPropagation()} className={`absolute cursor-move border px-4 py-2 text-sm font-bold shadow-lg ${button.style === 'pill' ? 'rounded-full' : button.style === 'rounded' ? 'rounded-xl' : 'rounded-none'} ${selectedLayer === button.id ? 'border-amber-300 ring-2 ring-amber-300/40' : 'border-transparent'}`} style={{ left: `${button.x}%`, top: `${button.y}%`, width: `${button.width}%`, background: button.backgroundColor, color: button.textColor }}>{button.label}</button>}</div></main>
      <aside className="max-h-[780px] overflow-y-auto border-t bg-white p-5 lg:border-l lg:border-t-0"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest">Layers</p><p className="text-xs text-slate-500">Select, drag, then fine-tune</p></div><button className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white" onClick={addBox}><Plus className="mr-1 inline size-3" />Text</button></div><div className="flex flex-col gap-2">{boxes.map((b, i) => <div key={b.id} className={`flex items-center gap-2 rounded-xl border p-2 ${selectedLayer === b.id ? 'border-amber-400 bg-amber-50' : 'border-slate-200'}`}><GripVertical className="size-4 text-slate-400" /><button className="min-w-0 flex-1 truncate text-left text-xs font-bold" onClick={() => setSelectedLayer(b.id)}>{i + 1}. {b.text || 'Text box'}</button><button onClick={() => patchLayer(b.id, { visible: !b.visible })}>{b.visible ? <Eye className="size-4" /> : <EyeOff className="size-4" />}</button><button onClick={() => removeLayer(b.id)}><Trash2 className="size-4 text-red-500" /></button></div>)}<div className={`flex items-center gap-2 rounded-xl border p-2 ${selectedLayer === button.id ? 'border-amber-400 bg-amber-50' : 'border-slate-200'}`}><GripVertical className="size-4 text-slate-400" /><button className="flex-1 text-left text-xs font-bold" onClick={() => setSelectedLayer(button.id)}>CTA button</button><button onClick={() => patchButton({ visible: !button.visible })}>{button.visible ? <Eye className="size-4" /> : <EyeOff className="size-4" />}</button></div></div>
        {selectedLayer && selectedLayer !== button.id && (() => { const b = boxes.find(x => x.id === selectedLayer); return b && <div className="mt-5 flex flex-col gap-3 border-t pt-4"><label className="text-xs font-bold">Text<textarea className="mt-1 min-h-20 w-full rounded-lg border p-2 text-sm" value={b.text} onChange={e => patchLayer(b.id, { text: e.target.value })} /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Font<select className="mt-1 w-full rounded-lg border p-2" value={b.fontFamily} onChange={e => patchLayer(b.id, { fontFamily: e.target.value as HeroTextBox['fontFamily'] })}><option value="sans">Sans</option><option value="serif">Serif</option><option value="mono">Mono</option></select></label><label className="text-xs font-bold">Size<input className="mt-1 w-full rounded-lg border p-2" type="number" min="10" max="120" value={b.fontSize} onChange={e => patchLayer(b.id, { fontSize: Number(e.target.value) })} /></label></div><label className="text-xs font-bold">Width <input className="w-full" type="range" min="10" max="90" value={b.width} onChange={e => patchLayer(b.id, { width: Number(e.target.value) })} /></label><label className="text-xs font-bold">Color<input className="ml-2 size-7 align-middle" type="color" value={b.color} onChange={e => patchLayer(b.id, { color: e.target.value })} /></label></div>; })()}
        {selectedLayer === button.id && <div className="mt-5 flex flex-col gap-3 border-t pt-4"><label className="text-xs font-bold">Button label<input className="mt-1 w-full rounded-lg border p-2" value={button.label} onChange={e => patchButton({ label: e.target.value })} /></label><label className="text-xs font-bold">Destination<select className="mt-1 w-full rounded-lg border p-2" value={button.destinationType + ':' + button.destination} onChange={e => { const [type, ...rest] = e.target.value.split(':'); patchButton({ destinationType: type as HeroButton['destinationType'], destination: rest.join(':') }); }}><option value="category:all">All products</option><option value="event:event_0209">Event page</option><option value="path:/shop">Internal /shop</option><option value="path:/collections">Internal /collections</option><option value="external:https://example.com">External URL</option></select></label><label className="text-xs font-bold">Width <input className="w-full" type="range" min="12" max="60" value={button.width} onChange={e => patchButton({ width: Number(e.target.value) })} /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Background<input className="ml-2 size-7 align-middle" type="color" value={button.backgroundColor} onChange={e => patchButton({ backgroundColor: e.target.value })} /></label><label className="text-xs font-bold">Text<input className="ml-2 size-7 align-middle" type="color" value={button.textColor} onChange={e => patchButton({ textColor: e.target.value })} /></label></div></div>}
        <div className="mt-6 border-t pt-4"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-4 text-xs font-bold"><ImagePlus className="size-4" />{uploading ? 'Uploading…' : `Upload ${device} artwork`}<input className="hidden" type="file" accept="image/*" onChange={e => upload(e.target.files?.[0])} /></label></div>
      </aside>
    </div>
  </div>;
}
